### ISSUE TITLE
Unable to purchase offer, throws error on lookup

### ISSUE THREAD

**Issue by sebastien1234** [syscoin/syscoin1#44] opened 2015-09-13 06:32 UTC
After creating an offer via console, searching the guid under "marketplace" returns the following error: "There was an exception trying to locate this offer, please check the offer ID and that it has been confirmed by the blockchain: value is type str, expected real"

GUID example: 

acdbf7a23526be74
27a920efd65f9af300

**Comment by dwasyluk** [comment] 2015-09-14 15:49
This issue has to do with "lookup guid" in the "Purchase Offer" tab, not "Search" tab- renamed issue. Not sure what the root cause is but here is the output from the debug log when running the search commands, and some contextual info as well:

My offers:
![screen shot 2015-09-14 at 11 45 44 am](https://cloud.githubusercontent.com/assets/987186/9854381/92c5a5ee-5ad6-11e5-87b8-9dc3afac290d.png)

My Purchase Offer Screen w/error:
![screen shot 2015-09-14 at 11 46 20 am](https://cloud.githubusercontent.com/assets/987186/9854376/8dab09fa-5ad6-11e5-9681-ed4ba101bd68.png)

Debug Output:
`2015-09-14 15:47:45 IsOfferMine() : found my transaction fb5833da57a97a6c7ac189acf47ba1c22d7f33e7d4e483baa24ba861edf99f93 nout 1`

**Comment by dwasyluk** [comment] 2015-09-16 05:15
verified fixed, closing.

**Closed as completed by dwasyluk** 2015-09-16 05:15 UTC
Labels: bug, shade-release
